### ISSUE TITLE
Vocab txt file?

### ISSUE THREAD

**Issue by ronentk** [olivettigroup/materials-synthesis-generative-models#1]
Hi, 
You reference the `vocab.txt` file [here](https://github.com/olivettigroup/materials-synthesis-generative-models/blob/73693c7efb8e0550a59b80e41593e62e3aa9d20b/models/token_classifier.py#L153) for example but I didn't understand which one is the default- is it a default ELMO vocabulary or one that you generated from mat-sci papers? I didn't see any at the links you provided.

Thanks for making these resources available!

**Comment by eddotman** [comment]
Apologies for the late reply -- must have missed this somehow. The default ELMo vocab files works perfectly fine in our experience. :)
