### ISSUE TITLE
Vocab file missing

### ISSUE THREAD

**Issue by sapan** [olivettigroup/materials-synthesis-generative-models#4]
Hi,
I am trying to use the pre-trained Elmo embeddings  for materials. However, I could not find the vocab file on figshare.
Request you to please share. I read that default vocab file works fine. In that case, where is this file located?

Many thanks in advance.

**Comment by eddotman** [comment]
This one should work: https://s3-us-west-2.amazonaws.com/allennlp/models/elmo/vocab-2016-09-10.txt

Caveat: I haven't looked at / used this code in a while. Someone active on the project (e.g., @zjensen262 might be able to help further if this doesn't work).

**Comment by sapan** [comment]
Thanks Edward, we had been able to run the code with vocab file.

**Comment by eddotman** [comment]
Great to hear it! Please feel free to ask if any other issues pop up.
